### ISSUE TITLE
Add P-vector beta factors for phase difference

### ISSUE THREAD

**Issue by redeboer** [ComPWA/K-matrix-research#31]
Currently, we do parametrize the single-channel $K$ matrix as:

![equation](https://github.com/ComPWA/K-matrix-research/assets/29308176/d232d14b-b851-480d-861f-f0707bdf496d)

Adding in coefficients $\beta_i$ for each term (which come from the production process through the [$P$ vector](https://ampform.readthedocs.io/en/0.14.x/usage/dynamics/k-matrix.html#p-vector), we get (forgetting about phase space factor $\rho$):

![equation](https://github.com/ComPWA/K-matrix-research/assets/29308176/0d0187ab-95c6-4dab-a663-4103c5d15659)

If we further parametrize these factors as $\beta_i = b_i e^{i\phi_i}$, we can nicely introduce a phase difference between the $K$ matrix terms with our sliders.

**Comment by Zeyna777** [comment]
Note for me: Beta factors inside formulate_kmatrix maybe define seperatly and then xreplace ?
